spring.datasource.url=jdbc:h2:mem:pnis_test;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.flyway.enabled=false
app.storage.upload-dir=./uploads-test
app.jwt.secret=TEST_SECRET_KEY_MUST_BE_AT_LEAST_64_CHARS_FOR_HS512_ALGORITHM_IN_TEST
