package com.pnis.backend.alert.model;

import com.pnis.backend.common.model.AbstractBaseEntity;
import jakarta.persistence.*;

import java.time.Instant;

@Entity
@Table(name = "alerts", indexes = {
        @Index(name = "idx_alert_tenant",   columnList = "tenant_id"),
        @Index(name = "idx_alert_status",   columnList = "alert_status"),
        @Index(name = "idx_alert_severity", columnList = "severity"),
        @Index(name = "idx_alert_type",     columnList = "alert_type"),
        @Index(name = "idx_alert_created",  columnList = "created_at")
})
public class Alert extends AbstractBaseEntity {

    @Column(name = "reference_code", nullable = false, unique = true, length = 60)
    private String referenceCode;

    @Column(nullable = false, length = 300)
    private String title;

    @Column(nullable = false, length = 8000)
    private String body;

    @Column(name = "alert_type", length = 50)
    private String alertType;

    @Column(name = "alert_status", nullable = false, length = 30)
    private String alertStatus = "DRAFT";

    @Column(length = 20)
    private String severity = "MEDIUM";

    @Column(name = "case_id")
    private Long caseId;

    @Column(name = "entity_id")
    private Long entityId;

    @Column(name = "geo_zone_id")
    private Long geoZoneId;

    private Double latitude;
    private Double longitude;
    private Double radiusMeters;

    @Column(name = "trigger_keywords", length = 500)
    private String triggerKeywords;

    @Column(name = "recipients", length = 2000)
    private String recipients;

    @Column(name = "published_to_pnis")
    private Boolean publishedToPnis = false;

    @Column(name = "published_at")
    private Instant publishedAt;

    @Column(name = "expires_at")
    private Instant expiresAt;

    @Column(name = "acknowledged_by", length = 100)
    private String acknowledgedBy;

    @Column(name = "acknowledged_at")
    private Instant acknowledgedAt;

    @Column(name = "lifted_reason", length = 1000)
    private String liftedReason;

    @Column(name = "lifted_at")
    private Instant liftedAt;

    @Column(name = "is_auto_generated")
    private Boolean isAutoGenerated = false;

    // ===== GETTERS =====
    public String  getReferenceCode()    { return referenceCode; }
    public String  getTitle()            { return title; }
    public String  getBody()             { return body; }
    public String  getAlertType()        { return alertType; }
    public String  getAlertStatus()      { return alertStatus; }
    public String  getSeverity()         { return severity; }
    public Long    getCaseId()           { return caseId; }
    public Long    getEntityId()         { return entityId; }
    public Long    getGeoZoneId()        { return geoZoneId; }
    public Double  getLatitude()         { return latitude; }
    public Double  getLongitude()        { return longitude; }
    public Double  getRadiusMeters()     { return radiusMeters; }
    public String  getTriggerKeywords()  { return triggerKeywords; }
    public String  getRecipients()       { return recipients; }
    public Boolean getPublishedToPnis()  { return publishedToPnis; }
    public Instant getPublishedAt()      { return publishedAt; }
    public Instant getExpiresAt()        { return expiresAt; }
    public String  getAcknowledgedBy()   { return acknowledgedBy; }
    public Instant getAcknowledgedAt()   { return acknowledgedAt; }
    public String  getLiftedReason()     { return liftedReason; }
    public Instant getLiftedAt()         { return liftedAt; }
    public Boolean getIsAutoGenerated()  { return isAutoGenerated; }

    // ===== SETTERS =====
    public void setReferenceCode(String v)   { this.referenceCode = v; }
    public void setTitle(String v)           { this.title = v; }
    public void setBody(String v)            { this.body = v; }
    public void setAlertType(String v)       { this.alertType = v; }
    public void setAlertStatus(String v)     { this.alertStatus = v; }
    public void setSeverity(String v)        { this.severity = v; }
    public void setCaseId(Long v)            { this.caseId = v; }
    public void setEntityId(Long v)          { this.entityId = v; }
    public void setGeoZoneId(Long v)         { this.geoZoneId = v; }
    public void setLatitude(Double v)        { this.latitude = v; }
    public void setLongitude(Double v)       { this.longitude = v; }
    public void setRadiusMeters(Double v)    { this.radiusMeters = v; }
    public void setTriggerKeywords(String v) { this.triggerKeywords = v; }
    public void setRecipients(String v)      { this.recipients = v; }
    public void setPublishedToPnis(Boolean v){ this.publishedToPnis = v; }
    public void setPublishedAt(Instant v)    { this.publishedAt = v; }
    public void setExpiresAt(Instant v)      { this.expiresAt = v; }
    public void setAcknowledgedBy(String v)  { this.acknowledgedBy = v; }
    public void setAcknowledgedAt(Instant v) { this.acknowledgedAt = v; }
    public void setLiftedReason(String v)    { this.liftedReason = v; }
    public void setLiftedAt(Instant v)       { this.liftedAt = v; }
    public void setIsAutoGenerated(Boolean v){ this.isAutoGenerated = v; }
}